parameters:
#    jaguirre_test_crud.example.class: Jaguirre\TestCRUDBundle\Example

services:
#    jaguirre_test_crud.example:
#        class: %jaguirre_test_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
