Acme\EventBundle\Entity\Participant:
    properties:
        code:
            - Max: { limit: 10, message: El codigo debe tener menos de 10 digitos }
            - Min: { limit: 4, message: El codigo debe tener menos de 10 digitos. }
	    - Type:
                type: integer
                message: El codigo {{ code }} no es un numero valido.

	name:
	    - MinLength: { limit: 4, message: "El nombre debe tener mas de 4 caracteres." }

	price:
	    - Type:
                type: integer
                message: El precio {{ code }} no es un numero valido.
	
